---
title: "ESM 244 Lab 1"
author: "Sydney Mayes"
date: "2023-01-13"
output: html_document
---

```{r setup, include=TRUE, echo=TRUE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(here)
library(sf)
library(tmap)
```

### Read in the data

```{r}
sf_trees <- read_csv(here('data', 'sf_trees', 'sf_trees.csv'))
# read.csv is the built in function; read_csv is an improved version from the tidyverse, has extra functionality and is faster
# summary(sf_trees); names(sf_trees)
# sf_trees %>% group_by(legal_status) %>% summarize(tree_count=n())
top_5_status <- sf_trees %>% 
  group_by(legal_status) %>% 
  summarize(tree_count = n()) %>% 
  slice_max(tree_count, n = 5) %>% 
  arrange(-tree_count)

ggplot(data = top_5_status, aes(x = fct_reorder(legal_status, tree_count),
                                y = tree_count)) +
  geom_col() +
  labs(y = 'Tree count', x = 'Legal Status') +
  coord_flip() +
  theme_minimal()
# ggplot is more general than ggpubr 


```
### Keep observations where legal status is 'Permitted Site' and caretaker is 'MTA'
```{r}
permitted_mta <- sf_trees %>% 
  filter(legal_status == "Permitted Site" & caretaker == "MTA")
# == means matches. single equals sign assigns a value
```

### Keep Blackwood acacia trees, only legal_status, latitute, longitude columns
```{r}
blackwood_acacia <- sf_trees %>% 
  filter(str_detect(species, "Blackwood Acacia")) %>% 
  select(legal_status, date, latitude, longitude)

### make a plot of SF acacia
ggplot(data = blackwood_acacia, aes(x = longitude, y = latitude)) +
  geom_point()
```
### Use tidyr::separate() to separate one column into multiple, and tidyr::unite() to rejoin 
```{r}
sf_trees_sep <- sf_trees %>% 
  separate(species, into = c('spp_scientific', 'spp_common'), sep = ' :: ')

sf_trees_unite <- sf_trees %>% 
  unite("id_status", tree_id:species, sep = '_NEW_')
```

### Make some actual maps !
```{r}
blackwood_acacia_sf <- blackwood_acacia %>% 
  drop_na(longitude, latitude) %>% 
  st_as_sf(coords = c('longitude', 'latitude'))
# sf stands for spatial features
st_crs(blackwood_acacia_sf) <- 4326 # coordinate reference system indicating basic latitude and longitude
ggplot(data=blackwood_acacia_sf) +
  geom_sf(color = 'darkgreen') + # always looking for a geometry column and will use it as aes
  theme_minimal()
  
```

#### read in SF streets data

```{r}
sf_map_sf <- read_sf(here('data', 'sf_map', 'tl_2017_06075_roads.shp')) %>% 
  st_transform(4326) # change the coordinate reference system
st_crs(sf_map_sf) # check to make sure it has changed
```

```{r}
ggplot() +
  geom_sf(data = sf_map_sf, size = 0.1, color = 'darkgrey') +
  geom_sf(data = blackwood_acacia_sf, color = 'red', size = 0.5) +
  theme_void()
  labs(title = 'Blackwood acacias in San Francisco')
```

### Interactive map!
```{r}
tmap_mode('view')
tm_shape(blackwood_acacia_sf) +
  tm_dots()
```



